export const GET_STANDING_REQUEST = 'GET_STANDING_REQUEST';
export const GET_STANDING_SUCCESS = 'GET_STANDING_SUCCESS';
export const GET_STANDING_FAILURE = 'GET_STANDING_FAILURE';


export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const UNLIKE_SUCCESS = 'UNLIKE_SUCCESS';